parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.6'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            geonames:
                url: '%env(resolve:GEONAMES_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.6'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
        types:
            json: App\Doctrine\DBAL\Types\UnescapedJsonType
            point: CrEOF\Spatial\DBAL\Types\Geometry\PointType

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                # https://symfony.com/doc/current/doctrine/custom_dql_functions.html
                # https://github.com/beberlei/DoctrineExtensions/blob/master/config/mysql.yml
                dql:
                    numeric_functions:
                        acos: DoctrineExtensions\Query\Mysql\Acos
                        cos: DoctrineExtensions\Query\Mysql\Cos
                        point: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Point
                        radians: DoctrineExtensions\Query\Mysql\Radians
                        sin: DoctrineExtensions\Query\Mysql\Sin
                        x: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\X
                        y: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Y
                    string_functions:
                        match: DoctrineExtensions\Query\Mysql\MatchAgainst
            geonames:
                connection: geonames
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
