doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                profiling_collect_backtrace: '%kernel.debug%'
            geonames:
                url: '%env(resolve:GEONAMES_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
        types:
            json: App\Doctrine\DBAL\Types\UnescapedJsonType
            point: CrEOF\Spatial\DBAL\Types\Geometry\PointType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                report_fields_where_declared: true
                validate_xml_mapping: true
                # https://symfony.com/doc/current/doctrine/custom_dql_functions.html
                # https://github.com/beberlei/DoctrineExtensions/blob/master/config/mysql.yml
                dql:
                    numeric_functions:
                        acos: DoctrineExtensions\Query\Mysql\Acos
                        cos: DoctrineExtensions\Query\Mysql\Cos
                        point: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Point
                        radians: DoctrineExtensions\Query\Mysql\Radians
                        sin: DoctrineExtensions\Query\Mysql\Sin
                        x: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\X
                        y: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Y
                    string_functions:
                        match: DoctrineExtensions\Query\Mysql\MatchAgainst
            geonames:
                connection: geonames
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
