monolog:
    channels:
        - deprecation
        - doctrine

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!doctrine", "!deprecation", "!security"]
            deprecation:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%-deprecation.log"
                level: debug
                channels: ["deprecation"]
            doctrine:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%-doctrine.log"
                level: debug
                channels: ["doctrine"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@prod:
    monolog:
        handlers:
            main:
                type: stream
                path: php://stderr
                level: info
                formatter: monolog.formatter.json
                channels: ["!event", "!doctrine", "!deprecation", "!security"]
#                type: fingers_crossed
#                # if *one* log is error or higher, pass *all* log entries for that request to the nested handler
#                action_level: error
#                handler: nested
#                excluded_http_codes: [404, 405]
#                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
#            nested:
#                type: stream
#                path: php://stderr
#                level: debug
#                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!deprecation"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
