twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        google_analytics_tag: '%google_analytics_tag%'

when@test:
    twig:
        strict_variables: true
